### ISSUE TITLE
Follow up on restructuring the APIs in modules

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/lionweb-repository#30]
I noticed two things after #29 was merged:
*  it seems there is this empty file left: https://github.com/LionWeb-io/lionweb-repository/blob/main/packages/core/src/controllers/LionWebBulkApiWorker.ts
* We may need to update the README to reflect on the changes

**Comment by joswarmer** [comment]
Oops, this file should have been removed.

**Comment by joswarmer** [comment]
Fixed in latest PR
