### ISSUE TITLE
Definition and publication of a Docker image

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/lionweb-repository#33]
It could be convenient for users to get access to a Docker image published in the official registry.

**Comment by joswarmer** [comment]
Good idea!

**Comment by joswarmer** [comment]
Would you prefer a docker image including Postgres + the repository-server, or just the repository-server?

**Comment by alessiostalla** [comment]
I think it's more common to have a separate image with just the application and to let the user combine it with other images (such as Postgres) possibly using something like Docker Compose.
FWIW we built a Docker image of the Lionweb repository for development with the following Dockerfile:
```
FROM node
RUN git clone https://github.com/LionWeb-io/lionweb-repository.git
WORKDIR lionweb-repository
RUN git checkout a966193
RUN npm install
RUN npm run build
RUN npm run lint
WORKDIR packages/server
ENV PGHOST=postgres
CMD ["npm", "run", "dev"]
```

which has at least two issues:
1) it's referring to a random Git commit because there are no release tags
2) it's using `npm run dev` to launch the repo, I don't know what the command does but "dev" suggests it's not something for production :)

We then have a simple Docker Compose file to launch the Postgres DB and the Lionweb Model Repository together.

**Comment by joswarmer** [comment]
@alessiostalla Tnx, as I am new to docker and docker compose, could you also share the docker compose file?

**Comment by joswarmer** [comment]
I am running both images in the same container. From the hoist I can access both the database and the repository server. However the repository server still cannot connect to the postgres server: connect ECONNREFUSED 127.0.0.1:5432

**Comment by joswarmer** [comment]
Ok, got it running now, had to set the environment variable PGHOST in the compose file.
Now the question is when and how often do we want to build the docker image and where do we want to publish it, so it is usable by others as well.

**Comment by joswarmer** [comment]
Could it be something like:
- always build and publish an image named "latest" when a PR is merged to main.
- build an image whenever a tag is created, named after the tag

**Comment by ftomassetti** [comment]
> Could it be something like:
> * always build and publish an image named "latest" when a PR is merged to main.
> * build an image whenever a tag is created, named after the tag

I think both would be useful, but if I had to pick one I would prefer the second one (use tags), as to me having reproducible builds is what matters the most

**Comment by alessiostalla** [comment]
Regarding our Compose file it's actually pretty simple and doesn't redeclare any env variables

**Comment by joswarmer** [comment]
@ftomassetti Can we close this?

**Comment by ftomassetti** [comment]
I think we have a local Dockerfile but we do not mention it in the Readme, and we do not publish it on the Docker registry (or I could not find it there):
<img width="1381" alt="Screenshot 2024-04-03 at 14 09 53" src="https://github.com/LionWeb-io/lionweb-repository/assets/439078/f363cd85-09dd-4d6a-93f0-be6b91b80568">

**Comment by joswarmer** [comment]
It will show on the github homepage of the repository project under "packages", there is none now, but just try it.

**Comment by ftomassetti** [comment]
Would it makes sense to publish the first version?
In this way we will have an example to refer to in the README.
If I understand correctly one would need to:
- create the git tag version.0.1.0
- update the version in package.json to be 0.1.1

Is that correct?
If it works for you I can do that

**Comment by joswarmer** [comment]
Yes, that sounds like a good idea.

**Comment by ftomassetti** [comment]
This is now done (I noticed the tag must be `release.*` to be picked up by the GitHub action doing a Docker release).

I created a PR to update the version (I did not feel like I could just commit on master) and I took advantage of the opportunity to add a few lines in the Readme about the release process and the docker image (#46 ).

I think this can now be closed. Thank you Jos!
