### ISSUE TITLE
Adding tags or release on NPM

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/lionweb-repository#36]
When using the lionweb-repository, it would be convenient to be able to refer to a specific version.
It would be ideal to have versions of npm which we can use. Alternatively it would be useful to have tags indicating various versions, as we would clone the repository, checkout the tag and build that specific version.
Without npm version or tags, we use scripts that just clone the repository and use the most recent commit. But that mean that when APIs change, tests that used to pass now fail

**Comment by joswarmer** [comment]
Npm releases do give stable versions, but in itself an npm release does not tell which commit is being used, we need tags or branches or something similar in the code repo as well.

**Comment by joswarmer** [comment]
We have this now, don't we?

**Comment by ftomassetti** [comment]
> We have this now, don't we?

I am not sure: I do now see tags, and I cannot find publications of this package in nom (I searched for the term "lionweb")
<img width="1591" alt="Screenshot 2024-04-03 at 14 04 24" src="https://github.com/LionWeb-io/lionweb-repository/assets/439078/c8e2b30d-97c4-4eda-b69b-c0554742c373">

Are NPM packages published somewhere?

**Comment by joswarmer** [comment]
By the way, did you push a version tag? I cannot se one.

**Comment by joswarmer** [comment]
Note that git needs a special command for pushing tags: 

    git push origin <tag_name>

**Comment by ftomassetti** [comment]
I have now pushed the tag (I delete a couple of tags I pushed by mistake)

**Comment by ftomassetti** [comment]
I think we have now the tags so I think we can close this one
