### ISSUE TITLE
Ensure that GitHub Actions run on PRs

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/lionweb-repository#54]
With PR #50 we (and by "we" I mean "I") broke the tests.
GitHub actions did not run for the PR, and so we (and by "we" I mean "Jos") noticed only after merging the PR.
It would be useful to have GitHub actions run for each PR, so that we can more easily prevent breaking the build.

**Comment by joswarmer** [comment]
It seems that actions don't run anymore, not even for simple pushes. Not sure why.

**Comment by joswarmer** [comment]
Its running again, both on push and for a PR.
