### ISSUE TITLE
server-config.json contains invalid JSON

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/lionweb-repository#70]
See:
https://github.com/LionWeb-io/lionweb-repository/blob/e9738d3191370df767c456d70102ddc808ea782a/packages/server/server-config.json#L14

`n+app` is not supposed to be there

**Comment by ftomassetti** [comment]
Note that the application started despite the file being invalid. I think it should have exited instead

**Comment by joswarmer** [comment]
> Note that the application started despite the file being invalid. I think it should have exited instead

I did this deliberately, as the file format isn't really validated completely.  But it probably is a good idea to fail starting the server if an error has been found.
