### ISSUE TITLE
Optimization experiment: create metapointers table

### ISSUE THREAD

**Issue by ftomassetti** [LionWeb-io/lionweb-repository#83]
Looking into a LW Repo I am working with I ran these queries:

```
select count(property_key) from "repository:default"."lionweb_properties";
result -> 2982498

select count(distinct(property_key)) from "repository:default"."lionweb_properties";
result -> 59
```

This means that on average every key is repeated more than 50,000 times.

This seems to indicate that we have a _lot_ of repeated metapointers. I wonder if insertions and retrieval could become faster if we created a table holding metapointers and then we had the other tables use a key to refer to the metapointers.

Entries in the Metapointers table would be immutable, so we could also keep a cache in the memory of the LW repo, to speed things up where needed.

Would this make any sense?

**Comment by dslmeinte** [comment]
Yes, this makes sense, both for memory and time optimization. Also, it probably simplifies queries.

**Comment by joswarmer** [comment]
It does make sense, had something like this in the back of my mind for some time. It will definitively save space (49,999 metapointers), but it would also mean an additional join during retrieval, not sure whether this will save or cost time.

**Comment by dslmeinte** [comment]
Luckily, databases (RDBMs) are pretty good at optimizing joins :)

**Comment by ftomassetti** [comment]
I wonder if, in other use cases, we can have a different average number of occurrences for the same metapointer. Having >50K occurences for a metapointer seems high.

I have no idea about performance, but I can try a few experiments and see how it looks like.

For my specific use case the performance problem is at insertion time, as I insert a lot of stuff at the same time. I expect to retrieve stuff element by element, so if it was up to me, I would sacrifice some speed on retrieval for a good speed boost on insertion, but I would be interested in hearing about other use cases where the requirements could be opposite.

**Comment by joswarmer** [comment]
> If you de-dup the metapointers before inserting them into the DB, would you avoid the performance problem. De-dupping in-memory is cheap, after all.
> 
> Also: would it make sense to populate the metapointers table when registering languages?

It does make sense, but the repo also needs to work without languages (as it does now).

**Comment by dslmeinte** [comment]
> > Also: would it make sense to populate the metapointers table when registering languages?
> 
> It does make sense, but the repo also needs to work without languages (as it does now).

Of course, but we could do the population at language “registration” (I guess: uploading/persisting) time, and otherwise de-dup and do UPSERTs if the languages are not there.

**Comment by joswarmer** [comment]
So I think this should be promoted from an 'experiment' into a 'ToDo' issue,

**Comment by joswarmer** [comment]
@ftomassetti You created a branch for the experiments you did. Is this branch still experimental, or could it be merged?

**Comment by ftomassetti** [comment]
@joswarmer sorry I should have updated this ticket. We introduced the table in this PR https://github.com/LionWeb-io/lionweb-repository/pull/86 so I will mark this issue as closed
